# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "books", :force => true do |t|
    t.column "isbn", :string, :limit => 10
    t.column "name", :string, :limit => 100
    t.column "author", :string, :limit => 100
    t.column "publisher", :string, :limit => 100
    t.column "created_by", :integer
    t.column "created_at", :datetime
    t.column "updated_by", :integer
    t.column "updated_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "name", :string, :limit => 40, :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
