# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "rucder_cruds", :force => true do |t|
    t.column "table_id", :integer, :default => 0,  :null => false
    t.column "log_id",   :integer, :default => 0,  :null => false
    t.column "name",     :string,  :default => "", :null => false
  end

  create_table "rucder_logs", :force => true do |t|
    t.column "sql",         :text
    t.column "parsed_sql",  :text
    t.column "stack_trace", :text
    t.column "created_at",  :datetime
  end

  create_table "rucder_tables", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "rucder_trace_lines", :force => true do |t|
    t.column "line",       :string
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
