# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "book_titles", :force => true do |t|
    t.column "title",     :string,               :default => "", :null => false
    t.column "authors",   :string,               :default => "", :null => false
    t.column "publisher", :string,               :default => "", :null => false
    t.column "isbn",      :string, :limit => 30, :default => "", :null => false
  end

  create_table "spec_links", :force => true do |t|
    t.column "url",          :string, :default => "", :null => false
    t.column "descriptions", :text
    t.column "external_url", :text
  end

end
