# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "parties", :force => true do |t|
    t.column "name", :string, :limit => 50, :null => false
    t.column "name_kana", :string, :limit => 50, :null => true
    t.column "tel", :string, :limit => 20, :null => false
  end

end
